sudo: required #superuser permission needed to execute the build
services:
  - docker #need a running docker ready to go

before_install: #Todo before deploying or running tests
  - docker build -t docker-workflow-tag -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-workflow-tag npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESS_KEY"
  secret_access_key:
    secure: "$SECRET"
  region: "ap-south-1"
  app: "docker-workflow"
  env: "DockerWorkflow-env"
  bucket_name: "elasticbeanstalk-ap-south-1-880750458821" #travis will zip all files from git and send to this s3 bucket

